### ISSUE TITLE
How to modify the loss function to apply to multi-label classification tasks

### ISSUE THREAD

**Issue by Xiangyu-Han** [facebookresearch/AlphaNet#10]
Hello, I applied it to multi-label classification tasks, but as the following scenario shows, the loss function does not converge. How do I modify my loss function?

Epoch: [0][4000/7176]	Time  2.197 ( 2.047)	Data  0.000 ( 0.010)	Loss -1.7713e+00 (-6.9243e-01)	Acc@1   0.13 (  0.13)	Acc@5   0.13 (  0.13)
Epoch: [0][4050/7176]	Time  1.978 ( 2.047)	Data  0.000 ( 0.010)	Loss -2.5454e+00 (-7.1199e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4100/7176]	Time  2.234 ( 2.048)	Data  0.000 ( 0.010)	Loss -3.2569e+00 (-7.2793e-01)	Acc@1   0.17 (  0.13)	Acc@5   0.17 (  0.13)
Epoch: [0][4150/7176]	Time  1.940 ( 2.048)	Data  0.000 ( 0.010)	Loss -1.6426e+00 (-7.5071e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4200/7176]	Time  2.101 ( 2.047)	Data  0.000 ( 0.010)	Loss -2.9430e+00 (-7.7234e-01)	Acc@1   0.13 (  0.13)	Acc@5   0.13 (  0.13)
Epoch: [0][4250/7176]	Time  2.056 ( 2.047)	Data  0.000 ( 0.009)	Loss -2.6333e+00 (-7.9679e-01)	Acc@1   0.20 (  0.13)	Acc@5   0.20 (  0.13)
Epoch: [0][4300/7176]	Time  2.002 ( 2.047)	Data  0.000 ( 0.009)	Loss -2.0716e+00 (-8.1554e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4350/7176]	Time  1.919 ( 2.048)	Data  0.000 ( 0.009)	Loss -1.1843e+00 (-8.3195e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4400/7176]	Time  1.972 ( 2.047)	Data  0.001 ( 0.009)	Loss -2.2746e+00 (-8.4905e-01)	Acc@1   0.20 (  0.13)	Acc@5   0.20 (  0.13)
Epoch: [0][4450/7176]	Time  2.151 ( 2.047)	Data  0.000 ( 0.009)	Loss -2.3914e+00 (-8.6940e-01)	Acc@1   0.19 (  0.13)	Acc@5   0.19 (  0.13)
Epoch: [0][4500/7176]	Time  1.873 ( 2.047)	Data  0.000 ( 0.009)	Loss -2.9244e+00 (-8.8694e-01)	Acc@1   0.12 (  0.13)	Acc@5   0.12 (  0.13)
Epoch: [0][4550/7176]	Time  2.112 ( 2.047)	Data  0.000 ( 0.009)	Loss -2.9324e+00 (-9.0775e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4600/7176]	Time  1.902 ( 2.047)	Data  0.000 ( 0.009)	Loss -2.0961e+00 (-9.2422e-01)	Acc@1   0.13 (  0.13)	Acc@5   0.13 (  0.13)
Epoch: [0][4650/7176]	Time  1.752 ( 2.047)	Data  0.000 ( 0.009)	Loss -1.9184e+00 (-9.3473e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4700/7176]	Time  1.967 ( 2.047)	Data  0.000 ( 0.009)	Loss -6.9974e-01 (-9.4724e-01)	Acc@1   0.15 (  0.13)	Acc@5   0.15 (  0.13)
Epoch: [0][4750/7176]	Time  1.994 ( 2.046)	Data  0.000 ( 0.009)	Loss -3.3847e+00 (-9.6442e-01)	Acc@1   0.15 (  0.13)	Acc@5   0.15 (  0.13)
Epoch: [0][4800/7176]	Time  2.085 ( 2.047)	Data  0.000 ( 0.008)	Loss -2.5070e+00 (-9.8096e-01)	Acc@1   0.15 (  0.13)	Acc@5   0.15 (  0.13)
Epoch: [0][4850/7176]	Time  1.899 ( 2.047)	Data  0.000 ( 0.008)	Loss -2.2142e+00 (-9.9467e-01)	Acc@1   0.14 (  0.13)	Acc@5   0.14 (  0.13)
Epoch: [0][4900/7176]	Time  2.096 ( 2.046)	Data  0.000 ( 0.008)	Loss -3.2781e+00 (-1.0132e+00)	Acc@1   0.19 (  0.13)	Acc@5   0.19 (  0.13)
Epoch: [0][4950/7176]	Time  1.782 ( 2.046)	Data  0.000 ( 0.008)	Loss -2.8195e+00 (-1.0289e+00)	Acc@1   0.17 (  0.13)	Acc@5   0.17 (  0.13)
Epoch: [0][5000/7176]	Time  1.996 ( 2.046)	Data  0.000 ( 0.008)	Loss -3.1988e+00 (-1.0456e+00)	Acc@1   0.18 (  0.13)	Acc@5   0.18 (  0.13)
Epoch: [0][5050/7176]	Time  2.248 ( 2.046)	Data  0.000 ( 0.008)	Loss -1.9582e+00 (-1.0614e+00)	Acc@1   0.13 (  0.13)	Acc@5   0.13 (  0.13)
Epoch: [0][5100/7176]	Time  2.029 ( 2.046)	Data  0.000 ( 0.008)	Loss -2.2378e+00 (-1.0686e+00)	Acc@1   0.18 (  0.13)	Acc@5   0.18 (  0.13)
Epoch: [0][5150/7176]	Time  1.943 ( 2.046)	Data  0.000 ( 0.008)	Loss -2.6617e+00 (-1.0803e+00)	Acc@1   0.15 (  0.13)	Acc@5   0.15 (  0.13)
Epoch: [0][5200/7176]	Time  2.050 ( 2.046)	Data  0.000 ( 0.008)	Loss -2.4670e+00 (-1.0952e+00)	Acc@1   0.17 (  0.13)	Acc@5   0.17 (  0.13)
Epoch: [0][5250/7176]	Time  2.051 ( 2.046)	Data  0.000 ( 0.008)	Loss -2.1453e+00 (-1.1098e+00)	Acc@1   0.20 (  0.13)	Acc@5   0.20 (  0.13)
Epoch: [0][5300/7176]	Time  2.064 ( 2.045)	Data  0.000 ( 0.008)	Loss -2.2843e+00 (-1.1214e+00)	Acc@1   0.18 (  0.13)	Acc@5   0.18 (  0.13)
Epoch: [0][5350/7176]	Time  2.232 ( 2.045)	Data  0.000 ( 0.008)	Loss -2.4472e+00 (-1.1356e+00)	Acc@1   0.16 (  0.13)	Acc@5   0.16 (  0.13)
Epoch: [0][5400/7176]	Time  1.980 ( 2.045)	Data  0.000 ( 0.008)	Loss -2.9187e+00 (-1.1485e+00)	Acc@1   0.18 (  0.14)	Acc@5   0.18 (  0.14)
Epoch: [0][5450/7176]	Time  2.144 ( 2.046)	Data  0.000 ( 0.007)	Loss -2.7685e+00 (-1.1622e+00)	Acc@1   0.16 (  0.14)	Acc@5   0.16 (  0.14)
Epoch: [0][5500/7176]	Time  1.839 ( 2.045)	Data  0.000 ( 0.007)	Loss -2.7240e+00 (-1.1766e+00)	Acc@1   0.12 (  0.14)	Acc@5   0.12 (  0.14)
Epoch: [0][5550/7176]	Time  1.953 ( 2.046)	Data  0.000 ( 0.007)	Loss -2.1483e+00 (-1.1920e+00)	Acc@1   0.15 (  0.14)	Acc@5   0.15 (  0.14)
Epoch: [0][5600/7176]	Time  1.842 ( 2.045)	Data  0.000 ( 0.007)	Loss -1.6526e+00 (-1.1999e+00)	Acc@1   0.17 (  0.14)	Acc@5   0.17 (  0.14)

**Comment by Xiangyu-Han** [comment]
Hello, I have another question, how should I search for a model whose accuracy does not decrease obviously but whose FLOPs are less than 200M?

**Comment by dilinwang820** [comment]
> Hello, I have another question, how should I search for a model whose accuracy does not decrease obviously but whose FLOPs are less than 200M?

Hi @Xiangyu-Han the smallest sub-network in this search has already had 200M FLOPs. You probably need to expand the search space a little bit to cover the FLOPs regime of your interest, and then fine-tune the existing supernet for a couple of epochs for good performance.
Or, you can try some small resolutions, e.g., 164 / 128, I guess the performance should still be reasonable.

**Comment by dilinwang820** [comment]
> Hello, I applied it to multi-label classification tasks, but as the following scenario shows, the loss function does not converge. How do I modify my loss function?
> 
> Epoch: [0][4000/7176] Time 2.197 ( 2.047) Data 0.000 ( 0.010) Loss -1.7713e+00 (-6.9243e-01) Acc@1 0.13 ( 0.13) Acc@5 0.13 ( 0.13) Epoch: [0][4050/7176] Time 1.978 ( 2.047) Data 0.000 ( 0.010) Loss -2.5454e+00 (-7.1199e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4100/7176] Time 2.234 ( 2.048) Data 0.000 ( 0.010) Loss -3.2569e+00 (-7.2793e-01) Acc@1 0.17 ( 0.13) Acc@5 0.17 ( 0.13) Epoch: [0][4150/7176] Time 1.940 ( 2.048) Data 0.000 ( 0.010) Loss -1.6426e+00 (-7.5071e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4200/7176] Time 2.101 ( 2.047) Data 0.000 ( 0.010) Loss -2.9430e+00 (-7.7234e-01) Acc@1 0.13 ( 0.13) Acc@5 0.13 ( 0.13) Epoch: [0][4250/7176] Time 2.056 ( 2.047) Data 0.000 ( 0.009) Loss -2.6333e+00 (-7.9679e-01) Acc@1 0.20 ( 0.13) Acc@5 0.20 ( 0.13) Epoch: [0][4300/7176] Time 2.002 ( 2.047) Data 0.000 ( 0.009) Loss -2.0716e+00 (-8.1554e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4350/7176] Time 1.919 ( 2.048) Data 0.000 ( 0.009) Loss -1.1843e+00 (-8.3195e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4400/7176] Time 1.972 ( 2.047) Data 0.001 ( 0.009) Loss -2.2746e+00 (-8.4905e-01) Acc@1 0.20 ( 0.13) Acc@5 0.20 ( 0.13) Epoch: [0][4450/7176] Time 2.151 ( 2.047) Data 0.000 ( 0.009) Loss -2.3914e+00 (-8.6940e-01) Acc@1 0.19 ( 0.13) Acc@5 0.19 ( 0.13) Epoch: [0][4500/7176] Time 1.873 ( 2.047) Data 0.000 ( 0.009) Loss -2.9244e+00 (-8.8694e-01) Acc@1 0.12 ( 0.13) Acc@5 0.12 ( 0.13) Epoch: [0][4550/7176] Time 2.112 ( 2.047) Data 0.000 ( 0.009) Loss -2.9324e+00 (-9.0775e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4600/7176] Time 1.902 ( 2.047) Data 0.000 ( 0.009) Loss -2.0961e+00 (-9.2422e-01) Acc@1 0.13 ( 0.13) Acc@5 0.13 ( 0.13) Epoch: [0][4650/7176] Time 1.752 ( 2.047) Data 0.000 ( 0.009) Loss -1.9184e+00 (-9.3473e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4700/7176] Time 1.967 ( 2.047) Data 0.000 ( 0.009) Loss -6.9974e-01 (-9.4724e-01) Acc@1 0.15 ( 0.13) Acc@5 0.15 ( 0.13) Epoch: [0][4750/7176] Time 1.994 ( 2.046) Data 0.000 ( 0.009) Loss -3.3847e+00 (-9.6442e-01) Acc@1 0.15 ( 0.13) Acc@5 0.15 ( 0.13) Epoch: [0][4800/7176] Time 2.085 ( 2.047) Data 0.000 ( 0.008) Loss -2.5070e+00 (-9.8096e-01) Acc@1 0.15 ( 0.13) Acc@5 0.15 ( 0.13) Epoch: [0][4850/7176] Time 1.899 ( 2.047) Data 0.000 ( 0.008) Loss -2.2142e+00 (-9.9467e-01) Acc@1 0.14 ( 0.13) Acc@5 0.14 ( 0.13) Epoch: [0][4900/7176] Time 2.096 ( 2.046) Data 0.000 ( 0.008) Loss -3.2781e+00 (-1.0132e+00) Acc@1 0.19 ( 0.13) Acc@5 0.19 ( 0.13) Epoch: [0][4950/7176] Time 1.782 ( 2.046) Data 0.000 ( 0.008) Loss -2.8195e+00 (-1.0289e+00) Acc@1 0.17 ( 0.13) Acc@5 0.17 ( 0.13) Epoch: [0][5000/7176] Time 1.996 ( 2.046) Data 0.000 ( 0.008) Loss -3.1988e+00 (-1.0456e+00) Acc@1 0.18 ( 0.13) Acc@5 0.18 ( 0.13) Epoch: [0][5050/7176] Time 2.248 ( 2.046) Data 0.000 ( 0.008) Loss -1.9582e+00 (-1.0614e+00) Acc@1 0.13 ( 0.13) Acc@5 0.13 ( 0.13) Epoch: [0][5100/7176] Time 2.029 ( 2.046) Data 0.000 ( 0.008) Loss -2.2378e+00 (-1.0686e+00) Acc@1 0.18 ( 0.13) Acc@5 0.18 ( 0.13) Epoch: [0][5150/7176] Time 1.943 ( 2.046) Data 0.000 ( 0.008) Loss -2.6617e+00 (-1.0803e+00) Acc@1 0.15 ( 0.13) Acc@5 0.15 ( 0.13) Epoch: [0][5200/7176] Time 2.050 ( 2.046) Data 0.000 ( 0.008) Loss -2.4670e+00 (-1.0952e+00) Acc@1 0.17 ( 0.13) Acc@5 0.17 ( 0.13) Epoch: [0][5250/7176] Time 2.051 ( 2.046) Data 0.000 ( 0.008) Loss -2.1453e+00 (-1.1098e+00) Acc@1 0.20 ( 0.13) Acc@5 0.20 ( 0.13) Epoch: [0][5300/7176] Time 2.064 ( 2.045) Data 0.000 ( 0.008) Loss -2.2843e+00 (-1.1214e+00) Acc@1 0.18 ( 0.13) Acc@5 0.18 ( 0.13) Epoch: [0][5350/7176] Time 2.232 ( 2.045) Data 0.000 ( 0.008) Loss -2.4472e+00 (-1.1356e+00) Acc@1 0.16 ( 0.13) Acc@5 0.16 ( 0.13) Epoch: [0][5400/7176] Time 1.980 ( 2.045) Data 0.000 ( 0.008) Loss -2.9187e+00 (-1.1485e+00) Acc@1 0.18 ( 0.14) Acc@5 0.18 ( 0.14) Epoch: [0][5450/7176] Time 2.144 ( 2.046) Data 0.000 ( 0.007) Loss -2.7685e+00 (-1.1622e+00) Acc@1 0.16 ( 0.14) Acc@5 0.16 ( 0.14) Epoch: [0][5500/7176] Time 1.839 ( 2.045) Data 0.000 ( 0.007) Loss -2.7240e+00 (-1.1766e+00) Acc@1 0.12 ( 0.14) Acc@5 0.12 ( 0.14) Epoch: [0][5550/7176] Time 1.953 ( 2.046) Data 0.000 ( 0.007) Loss -2.1483e+00 (-1.1920e+00) Acc@1 0.15 ( 0.14) Acc@5 0.15 ( 0.14) Epoch: [0][5600/7176] Time 1.842 ( 2.045) Data 0.000 ( 0.007) Loss -1.6526e+00 (-1.1999e+00) Acc@1 0.17 ( 0.14) Acc@5 0.17 ( 0.14)

Hi @Xiangyu-Han are the predictions (probabilities) normalized? Does the typical KL divergence work?

**Comment by Xiangyu-Han** [comment]
> > Hello, I have another question, how should I search for a model whose accuracy does not decrease obviously but whose FLOPs are less than 200M?
> 
> Hi @Xiangyu-Han the smallest sub-network in this search has already had 200M FLOPs. You probably need to expand the search space a little bit to cover the FLOPs regime of your interest, and then fine-tune the existing supernet for a couple of epochs for good performance. Or, you can try some small resolutions, e.g., 164 / 128, I guess the performance should still be reasonable.

Hello, if I expand my search space a little bit. Do you mean to change the mobileNet_v3 configuration parameters in the original train_alphanet_models.yml, such as change d:[3, 4] to d :[2, 3, 4], or should I add another layer structure?

**Comment by Xiangyu-Han** [comment]
> 
> Hi @Xiangyu-Han are the predictions (probabilities) normalized? Does the typical KL divergence work?

Yes，the predictions has already normalized. And I test the JS divergence and it works. But when I use the alpha loss function，I set criterion = nn.BCEWithLogitsLoss () for the multi-label classification task ( 31 categorys ), and in the AdaptiveLossSoft() loss function I modified the original softmax to sigmoid. At present, the accuracy is improved to 74%, but it is almost no longer improved. Besides, Loss is always negative and no longer converges. I don't know what I did wrong.

Epoch: [26][4000/9568]	Time  2.518 ( 2.036)	Data  0.000 ( 0.010)	Loss -1.8704e+00 (-1.7634e+00)	Acc@1   0.64 (  0.74)	Acc@5   0.64 (  0.74)
Epoch: [26][4050/9568]	Time  2.139 ( 2.036)	Data  0.000 ( 0.010)	Loss -1.7390e+00 (-1.7642e+00)	Acc@1   0.81 (  0.74)	Acc@5   0.81 (  0.74)
Epoch: [26][4100/9568]	Time  1.953 ( 2.036)	Data  0.000 ( 0.010)	Loss -1.9608e+00 (-1.7645e+00)	Acc@1   0.76 (  0.74)	Acc@5   0.76 (  0.74)
Epoch: [26][4150/9568]	Time  2.298 ( 2.036)	Data  0.000 ( 0.009)	Loss -1.8286e+00 (-1.7648e+00)	Acc@1   0.65 (  0.74)	Acc@5   0.65 (  0.74)
Epoch: [26][4200/9568]	Time  2.026 ( 2.036)	Data  0.000 ( 0.009)	Loss -1.7704e+00 (-1.7649e+00)	Acc@1   0.79 (  0.74)	Acc@5   0.79 (  0.74)
Epoch: [26][4250/9568]	Time  2.048 ( 2.036)	Data  0.000 ( 0.009)	Loss -1.9129e+00 (-1.7650e+00)	Acc@1   0.65 (  0.74)	Acc@5   0.65 (  0.74)
Epoch: [26][4300/9568]	Time  1.874 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.6845e+00 (-1.7643e+00)	Acc@1   0.70 (  0.74)	Acc@5   0.70 (  0.74)
Epoch: [26][4350/9568]	Time  2.228 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.8418e+00 (-1.7643e+00)	Acc@1   0.77 (  0.74)	Acc@5   0.77 (  0.74)
Epoch: [26][4400/9568]	Time  2.028 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.6786e+00 (-1.7642e+00)	Acc@1   0.68 (  0.74)	Acc@5   0.68 (  0.74)
Epoch: [26][4450/9568]	Time  2.068 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.7107e+00 (-1.7645e+00)	Acc@1   0.77 (  0.74)	Acc@5   0.77 (  0.74)
Epoch: [26][4500/9568]	Time  1.845 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.6940e+00 (-1.7650e+00)	Acc@1   0.73 (  0.74)	Acc@5   0.73 (  0.74)
Epoch: [26][4550/9568]	Time  1.957 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.3089e+00 (-1.7646e+00)	Acc@1   0.74 (  0.74)	Acc@5   0.74 (  0.74)
Epoch: [26][4600/9568]	Time  1.981 ( 2.035)	Data  0.000 ( 0.009)	Loss -1.9049e+00 (-1.7642e+00)	Acc@1   0.74 (  0.74)	Acc@5   0.74 (  0.74)
Epoch: [26][4650/9568]	Time  1.941 ( 2.035)	Data  0.000 ( 0.008)	Loss -1.6884e+00 (-1.7644e+00)	Acc@1   0.77 (  0.74)	Acc@5   0.77 (  0.74)
Epoch: [26][4700/9568]	Time  1.994 ( 2.034)	Data  0.000 ( 0.008)	Loss -1.7433e+00 (-1.7641e+00)	Acc@1   0.76 (  0.74)	Acc@5   0.76 (  0.74)
Epoch: [26][4750/9568]	Time  2.115 ( 2.034)	Data  0.000 ( 0.008)	Loss -1.8461e+00 (-1.7642e+00)	Acc@1   0.75 (  0.74)	Acc@5   0.75 (  0.74)
Epoch: [26][4800/9568]	Time  2.158 ( 2.034)	Data  0.000 ( 0.008)	Loss -1.8120e+00 (-1.7640e+00)	Acc@1   0.73 (  0.74)	Acc@5   0.73 (  0.74)
Epoch: [26][4850/9568]	Time  1.996 ( 2.034)	Data  0.000 ( 0.008)	Loss -1.5364e+00 (-1.7648e+00)	Acc@1   0.76 (  0.74)	Acc@5   0.76 (  0.74)
Epoch: [26][4900/9568]	Time  1.865 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.8115e+00 (-1.7647e+00)	Acc@1   0.69 (  0.74)	Acc@5   0.69 (  0.74)
Epoch: [26][4950/9568]	Time  2.037 ( 2.034)	Data  0.000 ( 0.008)	Loss -1.6236e+00 (-1.7646e+00)	Acc@1   0.75 (  0.74)	Acc@5   0.75 (  0.74)
Epoch: [26][5000/9568]	Time  1.845 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.9019e+00 (-1.7635e+00)	Acc@1   0.83 (  0.74)	Acc@5   0.83 (  0.74)
Epoch: [26][5050/9568]	Time  2.319 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.8865e+00 (-1.7628e+00)	Acc@1   0.69 (  0.74)	Acc@5   0.69 (  0.74)
Epoch: [26][5100/9568]	Time  1.939 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.8403e+00 (-1.7620e+00)	Acc@1   0.79 (  0.74)	Acc@5   0.79 (  0.74)
Epoch: [26][5150/9568]	Time  2.091 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.6821e+00 (-1.7615e+00)	Acc@1   0.67 (  0.74)	Acc@5   0.67 (  0.74)
Epoch: [26][5200/9568]	Time  2.017 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.7527e+00 (-1.7602e+00)	Acc@1   0.73 (  0.74)	Acc@5   0.73 (  0.74)
Epoch: [26][5250/9568]	Time  1.907 ( 2.033)	Data  0.000 ( 0.008)	Loss -1.6444e+00 (-1.7595e+00)	Acc@1   0.74 (  0.74)	Acc@5   0.74 (  0.74)
Epoch: [26][5300/9568]	Time  1.938 ( 2.032)	Data  0.000 ( 0.007)	Loss -1.5563e+00 (-1.7589e+00)	Acc@1   0.81 (  0.74)	Acc@5   0.81 (  0.74)
Epoch: [26][5350/9568]	Time  1.724 ( 2.032)	Data  0.000 ( 0.007)	Loss -1.6942e+00 (-1.7585e+00)	Acc@1   0.70 (  0.74)	Acc@5   0.70 (  0.74)
Epoch: [26][5400/9568]	Time  2.074 ( 2.032)	Data  0.000 ( 0.007)	Loss -1.7211e+00 (-1.7582e+00)	Acc@1   0.77 (  0.74)	Acc@5   0.77 (  0.74)
Epoch: [26][5450/9568]	Time  2.008 ( 2.032)	Data  0.000 ( 0.007)	Loss -1.6550e+00 (-1.7574e+00)	Acc@1   0.73 (  0.74)	Acc@5   0.73 (  0.74)
Epoch: [26][5500/9568]	Time  2.359 ( 2.032)	Data  0.000 ( 0.007)	Loss -1.7748e+00 (-1.7573e+00)	Acc@1   0.74 (  0.74)	Acc@5   0.74 (  0.74)

**Comment by dilinwang820** [comment]
Feel free to re-open if the issue is still not addressed.
