### ISSUE TITLE
there are some files missing or I can't find them

### ISSUE THREAD

**Issue by yangyang90** [facebookresearch/AlphaNet#12]
I run the test_alphanet.py with python test_alphanet.py --config-file ./configs/eval_alphanet_models.yml --model a[0-6]
then it reports an error **ModuleNotFouror: No module named 'models'**
![e325f2655ca89622384e291e6a9b2f5](https://user-images.githubusercontent.com/65580046/179906854-4a6d7796-516c-4173-a3d2-779899f9abc8.jpg)

I lookup the files but i can't find **_models_** and some others in the picture in the files
![c3ac0ae0e00da9e2c2b5b666491c5e6](https://user-images.githubusercontent.com/65580046/179906818-7410ad5a-9ead-4520-8996-ceb3988b122d.jpg)

thanks
ps:I'm a rookie so i maybe make low-level mistakes

**Comment by dilinwang820** [comment]
Hi @yangyang90 our code has a dependency on this repo (https://github.com/facebookresearch/AttentiveNAS). Please see the README.
