### ISSUE TITLE
How can I preserve the search architecture？

### ISSUE THREAD

**Issue by howardgriffin** [facebookresearch/AlphaNet#4]
Hi，when testing, I found it use the default architecture(a0~a6) you provided in eval_alphanet_model.yaml. How should I preserve my own architecture when training the searching stage?

**Comment by dilinwang820** [comment]
Hi, you can specify your own sub-network by passing its configurations here - 
https://github.com/facebookresearch/AttentiveNAS/blob/master/models/attentive_nas_dynamic_model.py#L207

To evaluate a sub-network through supernet, you can follow the code here - 
https://github.com/facebookresearch/AttentiveNAS/blob/master/evaluate/attentive_nas_eval.py#L20

You can also create a standalone network by copying the weights from the supernet, please see - 
https://github.com/facebookresearch/AttentiveNAS/blob/master/models/attentive_nas_dynamic_model.py#L365

**Comment by howardgriffin** [comment]
Maybe I didn't express what I meant. What puzzles me is where the architecture (a0~a6) comes from, e.g. how to get the architecture parameters of a0?
![image](https://user-images.githubusercontent.com/23454942/124341091-b4fa4f00-dbec-11eb-87da-fad94a2e11bc.png)

**Comment by fanliaveline** [comment]
This problem also puzzles me.  How to save the architecture parameters to a file? Thank you very much!

**Comment by fanliaveline** [comment]
Hello，this problem also puzzles me. I want to konw that how to choose these architecture parameters. In other words，how can I get my own a0-a6 ？

**Comment by maryanpetruk** [comment]
Hello @dilinwang820

Do you plan to publish the code to search for subnetworks from the supernet?
In the paper you mention evolutionary algorithms.

**Comment by dilinwang820** [comment]
@howardgriffin  As you can see from the model names, **_attentive_nas_a[0-6]_** are the models we found in the AttentiveNAS paper. Here we directly evaluate their performance using the supernet weights trained with our adaptive strategy. 

Particularly, AttentiveNAS models are searched for the best FLOPs vs. accuracy tradeoffs. @fanliaveline  you might want to code up your own evolutionary search algorithm to search the Pareto models of your interest.

**Comment by dilinwang820** [comment]
Hi @howardgriffin @fanliaveline  @maryanpetruk 
We have now included an example of evolutionary search code in this repo; see the updated README. Thanks.
