### ISSUE TITLE
evolutionary search in a single gpu

### ISSUE THREAD

**Issue by aswanthkrishna** [facebookresearch/AlphaNet#5]
is it possible to do the evolutionary search in single GPU

**Comment by dilinwang820** [comment]
Sure, in this case, you will need to remove all DDP settings.

**Comment by aswanthkrishna** [comment]
what should i do to remove the DDP settings?

**Comment by dilinwang820** [comment]
You may consider following the ImageNet training example here - https://github.com/pytorch/examples/blob/master/imagenet/main.py

This training code supports both DistributedDataParallel and DataParallel training. Thanks.

**Comment by aswanthkrishna** [comment]
thanks for your help!
