### ISSUE TITLE
Can Adaptive-KD use with additional attentive sampling  at the same time ?

### ISSUE THREAD

**Issue by DehuaTang** [facebookresearch/AlphaNet#7]
Hello,

       Can Adaptive-KD use with additional attentive sampling  at the same time ?  Are these two methods orthogonal？

Thank you

**Comment by dilinwang820** [comment]
Yes, they're orthogonal techniques. In this work, we find adaptive-KD alone can already give us very promising results and hence, we did not further explore the addition of attentive sampling for the sake of simplicity.

**Comment by DehuaTang** [comment]
Nice wok ! Thank you for your reply. Adaptive-KD loss  work well in my task !

**Comment by fanliaveline** [comment]
> Nice wok ! Thank you for your reply. Adaptive-KD loss work well in my task !

Hello! Did you use the Adaptive-KD loss with attentive sampling in your task?
