### ISSUE TITLE
Re-training code is available?

### ISSUE THREAD

**Issue by Jxu-Thu** [facebookresearch/AlphaNet#8]
Thanks for your great codes!
after running the alphanet, I would like to re-train the searched model. Can you provide the re-training code?

**Comment by dilinwang820** [comment]
Sorry, I don't have the re-training code for single networks. This seems a nice example to me - https://github.com/pytorch/examples/blob/master/imagenet/main.py

**Comment by Jxu-Thu** [comment]
Thanks!
